import localFont from "next/font/local";
import { Encode_Sans_Condensed } from "next/font/google"; // Import the Google Font
import "./globals.css";

// Importing the Google Font: Encode Sans Condensed
const encodeSansCondensed = Encode_Sans_Condensed({
  weight: ["400", "700"], // You can specify the weights you want to use
  subsets: ["latin"], // You can adjust the subsets if needed
  variable: "--font-encode-sans-condensed",
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={` ${encodeSansCondensed.className} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
